title: Eric Wang
email: ewang10532@gmail.com
description: Data Scientist with a background in statistics, machine learning, and applied AI.
baseurl: ""
url: "https://ewang229.github.io"

github_username: EWang229
linkedin_username: ewwang

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - resume.markdown